language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - wget https://keys.algolia.engineering/client/algolia-keys && chmod +x algolia-keys
  - composer self-update
  - composer install --no-interaction

script:
  - php artisan key:generate
  - $(./algolia-keys export) && vendor/bin/phpunit

services:
  - redis-server

cache:
  directories:
    - vendor
